---
apiVersion: v1
kind: Service
metadata:
  namespace: custom-app
  name: my-custom-app
  labels:
    app: my-custom-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    app: my-custom-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-app
  namespace: custom-app
  labels:
    app: my-custom-app
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: my-custom-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-custom-app
    spec:
      containers:
      - name: my-custom-app-container
        image: <image-url>
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: CUSTOM_APP